-- 01_vw_reporting_table.sql

CREATE OR REPLACE VIEW VW_REPORTING_TABLE AS
WITH SALES_DETAIL AS (
  SELECT
    s.SALE_ID,
    s.SALE_TIME,
    CAST(s.SALE_TIME AS DATE) AS SALE_DATE,
    s.ITEM_ID,
    COALESCE(i.ITEM_NAME, s.ITEM_NAME) AS ITEM_NAME,
    s.VENDOR_ID,
    s.POS_ID,
    s.EMPLOYEE_ID,
    s.UNITS_SOLD,
    s.GROSS_SALES,
    s.NET_SALES,
    s.DISCOUNTS,
    s.DISCOUNT_NAME,

    -- Item details
    i.ITEM_PRICE,
    i.ITEM_COST,
    i.ITEM_GROUP,
    i.ITEM_CATEGORY,
    i.ITEM_SUBCATEGORY,

    -- Stand details
    l.STAND_NAME,
    l.DEPARTMENT,
    l.STAND_TYPE,
    l.ARENA_LEVEL

  FROM SRC_RAW_SALES_BY_ITEM s
  LEFT JOIN LKP_ITEM_DETAILS i
    ON s.ITEM_ID = i.ITEM_ID
  LEFT JOIN LKP_STAND_LOCATIONS l
    ON s.VENDOR_ID = l.VENDOR_ID
)

SELECT
  sd.*,

  -- Event details
  e.EVENT_TYPE,
  e.EVENT_DATE,
  e.SEASON,
  e.EVENT_START_TIME,
  e.DAY_OF_WEEK,
  e.EVENT_NAME,
  e.EVENT_GENRE,
  e.EVENT_TIER,
  e.GENERAL_ATTENDANCE,
  e.CLUB_ATTENDANCE,
  e.SUITE_ATTENDANCE,
  e.COURTSIDE_ATTENDANCE,
  e.TOTAL_ATTENDANCE

FROM SALES_DETAIL sd
LEFT JOIN LKP_EVENTS_CALENDAR e
  ON sd.SALE_DATE = e.EVENT_DATE;
