-- 02_core_kpis.sql
-- Event-level KPI framework (one row per event)
-- Notes:
-- - Transactions are COUNT(DISTINCT SALE_ID) because sales are item-level lines
-- - Uses NULLIF to avoid divide-by-zero
-- - Filters out orphan sales that failed event attribution (optional; see below)

SELECT
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,
  TOTAL_ATTENDANCE,

  -- Sales totals
  SUM(GROSS_SALES) AS GROSS_SALES,
  SUM(NET_SALES)   AS NET_SALES,
  SUM(DISCOUNTS)   AS DISCOUNTS,
  SUM(DISCOUNTS) / NULLIF(SUM(GROSS_SALES), 0) AS DISCOUNT_RATE,

  -- Core volume metrics
  SUM(UNITS_SOLD) AS UNITS_SOLD,
  COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
  COUNT(DISTINCT POS_ID)  AS POS_COUNT,

  -- KPI Framework
  SUM(NET_SALES) / NULLIF(TOTAL_ATTENDANCE, 0) AS PER_CAP,
  COUNT(DISTINCT SALE_ID) * 1.0 / NULLIF(TOTAL_ATTENDANCE, 0) AS CONVERSION,
  SUM(UNITS_SOLD) * 1.0 / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS BASKET_SIZE,
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS AVG_TICKET,

  -- Ops/throughput proxy (helpful for staffing conversations)
  COUNT(DISTINCT SALE_ID) * 1.0 / NULLIF(COUNT(DISTINCT POS_ID), 0) AS TXNS_PER_POS

  -- Menu Mix % of Net Sales (ideal to showcase spending behaviors of different crowds)
  SUM(CASE WHEN ITEM_CATEGORY = 'FOOD' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS FOOD_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'NON-ALCOHOL' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS NA_BEV_SALES_PCT,

  -- Alcohol split: Beer / Liquor / Wine (Wine will be 0.0 unless you add wine items)
  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'BEER' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS BEER_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'LIQUOR' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS LIQUOR_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'WINE' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS WINE_SALES_PCT,

FROM VW_REPORTING_TABLE
WHERE EVENT_NAME IS NOT NULL
GROUP BY 
  EVENT_DATE, EVENT_TYPE, EVENT_NAME, EVENT_TIER,
  SEASON, DAY_OF_WEEK, EVENT_START_TIME, TOTAL_ATTENDANCE
ORDER BY EVENT_DATE, EVENT_START_TIME;
