-- 03_attendance_segments.sql
-- Segment KPIs by arena level (GENERAL / CLUB / SUITE / COURTSIDE)
-- Arena level is sourced from LKP_STAND_LOCATIONS and mapped in VW_REPORTING_TABLE.

WITH BASE AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,

    ARENA_LEVEL,
    SALE_ID,
    POS_ID,
    UNITS_SOLD,
    GROSS_SALES,
    NET_SALES,
    DISCOUNTS,
    ITEM_CATEGORY,
    ITEM_SUBCATEGORY,

    -- Attendance fields (same for all rows in the event, so we'll MAX them)
    GENERAL_ATTENDANCE,
    CLUB_ATTENDANCE,
    SUITE_ATTENDANCE,
    COURTSIDE_ATTENDANCE
  FROM VW_REPORTING_TABLE
  WHERE EVENT_NAME IS NOT NULL
),

SEGMENT_AGG AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,
    ARENA_LEVEL,

    SUM(NET_SALES) AS NET_SALES,
    SUM(GROSS_SALES) AS GROSS_SALES,
    SUM(DISCOUNTS) AS DISCOUNTS,
    SUM(UNITS_SOLD) AS UNITS_SOLD,
    COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
    COUNT(DISTINCT POS_ID) AS POS_COUNT,

    -- Mix (aligned to CSV categories)
    SUM(CASE WHEN ITEM_CATEGORY = 'FOOD' THEN NET_SALES ELSE 0 END) AS FOOD_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'NON-ALCOHOL' THEN NET_SALES ELSE 0 END) AS NA_BEV_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'BEER' THEN NET_SALES ELSE 0 END) AS BEER_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'LIQUOR' THEN NET_SALES ELSE 0 END) AS LIQUOR_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'WINE' THEN NET_SALES ELSE 0 END) AS WINE_SALES

  FROM BASE
  GROUP BY
    EVENT_DATE, EVENT_TYPE, EVENT_NAME, EVENT_TIER, SEASON, DAY_OF_WEEK, EVENT_START_TIME,
    ARENA_LEVEL
),

EVENT_ATT AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    MAX(GENERAL_ATTENDANCE) AS GENERAL_ATTENDANCE,
    MAX(CLUB_ATTENDANCE) AS CLUB_ATTENDANCE,
    MAX(SUITE_ATTENDANCE) AS SUITE_ATTENDANCE,
    MAX(COURTSIDE_ATTENDANCE) AS COURTSIDE_ATTENDANCE
  FROM BASE
  GROUP BY EVENT_DATE, EVENT_TYPE, EVENT_NAME
)

SELECT
  s.EVENT_DATE,
  s.EVENT_TYPE,
  s.EVENT_NAME,
  s.EVENT_TIER,
  s.SEASON,
  s.DAY_OF_WEEK,
  s.EVENT_START_TIME,
  s.ARENA_LEVEL,

  -- Pick the correct attendance denominator based on arena level
  CASE
    WHEN s.ARENA_LEVEL = 'GENERAL'   THEN a.GENERAL_ATTENDANCE
    WHEN s.ARENA_LEVEL = 'CLUB'      THEN a.CLUB_ATTENDANCE
    WHEN s.ARENA_LEVEL = 'SUITE'     THEN a.SUITE_ATTENDANCE
    WHEN s.ARENA_LEVEL = 'COURTSIDE' THEN a.COURTSIDE_ATTENDANCE
  END AS SEGMENT_ATTENDANCE,

  -- Totals
  s.NET_SALES,
  s.GROSS_SALES,
  s.DISCOUNTS,
  s.UNITS_SOLD,
  s.TRANSACTIONS,
  s.POS_COUNT,

  -- Segment KPIs
  s.NET_SALES / NULLIF(SEGMENT_ATTENDANCE, 0) AS SEGMENT_PER_CAP,
  s.TRANSACTIONS / NULLIF(SEGMENT_ATTENDANCE, 0) AS SEGMENT_CONVERSION,
  s.UNITS_SOLD / NULLIF(s.TRANSACTIONS, 0) AS SEGMENT_BASKET_SIZE,
  s.NET_SALES / NULLIF(s.TRANSACTIONS, 0) AS SEGMENT_CHECK_AVG,
  s.TRANSACTIONS / NULLIF(s.POS_COUNT, 0) AS SEGMENT_TXNS_PER_POS,

  -- Mix percentages (of segment net sales)
  s.FOOD_SALES   / NULLIF(s.NET_SALES, 0) AS FOOD_SALES_PCT,
  s.NA_BEV_SALES / NULLIF(s.NET_SALES, 0) AS NA_BEV_SALES_PCT,
  s.BEER_SALES   / NULLIF(s.NET_SALES, 0) AS BEER_SALES_PCT,
  s.LIQUOR_SALES / NULLIF(s.NET_SALES, 0) AS LIQUOR_SALES_PCT,
  s.WINE_SALES   / NULLIF(s.NET_SALES, 0) AS WINE_SALES_PCT

FROM SEGMENT_AGG s
JOIN EVENT_ATT a
  ON s.EVENT_DATE = a.EVENT_DATE
 AND s.EVENT_TYPE = a.EVENT_TYPE
 AND s.EVENT_NAME = a.EVENT_NAME

ORDER BY s.EVENT_DATE, s.EVENT_START_TIME, s.ARENA_LEVEL;
