-- 04_stand_performance.sql
-- Stand-level operational performance by event
-- Focus: throughput, efficiency, and revenue mix

SELECT
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,

  -- Stand dimensions
  VENDOR_ID,
  STAND_NAME,
  DEPARTMENT,
  STAND_TYPE,
  ARENA_LEVEL,

  -- Core totals
  SUM(NET_SALES) AS NET_SALES,
  SUM(GROSS_SALES) AS GROSS_SALES,
  SUM(DISCOUNTS) AS DISCOUNTS,
  SUM(UNITS_SOLD) AS UNITS_SOLD,

  COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
  COUNT(DISTINCT POS_ID) AS POS_COUNT,

  -- Efficiency & throughput metrics
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT POS_ID), 0) AS SALES_PER_POS,
  COUNT(DISTINCT SALE_ID) * 1.0 / NULLIF(COUNT(DISTINCT POS_ID), 0) AS TXNS_PER_POS,
  SUM(UNITS_SOLD) * 1.0 / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS BASKET_SIZE,
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS CHECK_AVG,

  -- Discount rate (ops signal)
  SUM(DISCOUNTS) / NULLIF(SUM(GROSS_SALES), 0) AS DISCOUNT_RATE,

  -- Menu / category mix (aligned to CSV categories)
  SUM(CASE WHEN ITEM_CATEGORY = 'FOOD' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS FOOD_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'NON-ALCOHOL' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS NA_BEV_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'BEER' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS BEER_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'LIQUOR' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS LIQUOR_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'WINE' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS WINE_SALES_PCT

FROM VW_REPORTING_TABLE
WHERE EVENT_NAME IS NOT NULL
GROUP BY
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,
  VENDOR_ID,
  STAND_NAME,
  DEPARTMENT,
  STAND_TYPE,
  ARENA_LEVEL
ORDER BY
  EVENT_DATE,
  EVENT_START_TIME,
  NET_SALES DESC;
