-- 05_item_mix_margin.sql
-- Item-level performance and estimated margin analysis
-- Margin is estimated using ITEM_COST from LKP_ITEM_DETAILS

SELECT
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,

  -- Item dimensions
  ITEM_ID,
  ITEM_NAME,
  ITEM_GROUP,
  ITEM_CATEGORY,
  ITEM_SUBCATEGORY,

  -- Volume & revenue
  SUM(UNITS_SOLD) AS UNITS_SOLD,
  COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
  SUM(GROSS_SALES) AS GROSS_SALES,
  SUM(NET_SALES) AS NET_SALES,
  SUM(DISCOUNTS) AS DISCOUNTS,

  -- Estimated cost & margin
  SUM(UNITS_SOLD * ITEM_COST) AS EST_COGS,
  SUM(NET_SALES) - SUM(UNITS_SOLD * ITEM_COST) AS EST_GROSS_MARGIN,
  (SUM(NET_SALES) - SUM(UNITS_SOLD * ITEM_COST))
    / NULLIF(SUM(NET_SALES), 0) AS EST_MARGIN_PCT,

  -- Item behavior KPIs
  SUM(UNITS_SOLD) / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS UNITS_PER_TXN,
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS REV_PER_TXN,

  -- Discount exposure
  SUM(DISCOUNTS) / NULLIF(SUM(GROSS_SALES), 0) AS DISCOUNT_RATE

FROM VW_REPORTING_TABLE
WHERE EVENT_NAME IS NOT NULL
GROUP BY
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,
  ITEM_ID,
  ITEM_NAME,
  ITEM_GROUP,
  ITEM_CATEGORY,
  ITEM_SUBCATEGORY
ORDER BY
  EVENT_DATE,
  EVENT_START_TIME,
  NET_SALES DESC;
