-- 06_time_buckets_15min.sql
-- Time-based demand analysis using 15-minute buckets relative to event start
-- Supports staffing, throughput, and operational planning

WITH BASE AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,

    SALE_ID,
    POS_ID,
    SALE_TIME,
    UNITS_SOLD,
    GROSS_SALES,
    NET_SALES,
    DISCOUNTS,
    ITEM_CATEGORY,
    ITEM_SUBCATEGORY,

    -- Minutes relative to event start
    DATEDIFF(minute, EVENT_START_TIME, SALE_TIME) AS MINUTES_FROM_START
  FROM VW_REPORTING_TABLE
  WHERE EVENT_NAME IS NOT NULL
),

BUCKETED AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,

    -- 15-minute bucket (relative)
    FLOOR(MINUTES_FROM_START / 15) * 15 AS MINUTE_BUCKET,

    -- Phase classification
    CASE
      WHEN MINUTES_FROM_START < 0 THEN 'PRE_EVENT'
      WHEN MINUTES_FROM_START BETWEEN 0 AND 120 THEN 'IN_EVENT'
      ELSE 'POST_EVENT'
    END AS EVENT_PHASE,

    SALE_ID,
    POS_ID,
    UNITS_SOLD,
    GROSS_SALES,
    NET_SALES,
    DISCOUNTS,
    ITEM_CATEGORY,
    ITEM_SUBCATEGORY
  FROM BASE
)

SELECT
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,

  EVENT_PHASE,
  MINUTE_BUCKET,

  -- Core totals
  SUM(NET_SALES) AS NET_SALES,
  SUM(GROSS_SALES) AS GROSS_SALES,
  SUM(DISCOUNTS) AS DISCOUNTS,
  SUM(UNITS_SOLD) AS UNITS_SOLD,

  COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
  COUNT(DISTINCT POS_ID) AS POS_COUNT,

  -- Throughput & efficiency
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT POS_ID), 0) AS SALES_PER_POS,
  COUNT(DISTINCT SALE_ID) * 1.0 / NULLIF(COUNT(DISTINCT POS_ID), 0) AS TXNS_PER_POS,
  SUM(UNITS_SOLD) * 1.0 / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS BASKET_SIZE,
  SUM(NET_SALES) / NULLIF(COUNT(DISTINCT SALE_ID), 0) AS AVG_TICKET,

  -- Category mix (aligned to CSV categories)
  SUM(CASE WHEN ITEM_CATEGORY = 'FOOD' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS FOOD_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'NON-ALCOHOL' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS NA_BEV_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'BEER' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS BEER_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'LIQUOR' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS LIQUOR_SALES_PCT,

  SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'WINE' THEN NET_SALES ELSE 0 END)
    / NULLIF(SUM(NET_SALES), 0) AS WINE_SALES_PCT

FROM BUCKETED
GROUP BY
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,
  EVENT_PHASE,
  MINUTE_BUCKET
ORDER BY
  EVENT_DATE,
  EVENT_START_TIME,
  MINUTE_BUCKET;
