-- 07_discounts_promos.sql
-- Promotion and discount impact analysis
-- Focus: effectiveness, leakage, and mix shifts

WITH BASE AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,

    SALE_ID,
    POS_ID,
    ITEM_CATEGORY,
    ITEM_SUBCATEGORY,

    GROSS_SALES,
    NET_SALES,
    DISCOUNTS,
    UNITS_SOLD,

    -- Promo flags
    CASE WHEN DISCOUNT_NAME IS NOT NULL THEN 1 ELSE 0 END AS IS_DISCOUNTED,
    COALESCE(DISCOUNT_NAME, 'NO_DISCOUNT') AS DISCOUNT_NAME
  FROM VW_REPORTING_TABLE
  WHERE EVENT_NAME IS NOT NULL
),

AGG AS (
  SELECT
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,

    IS_DISCOUNTED,
    DISCOUNT_NAME,

    -- Totals
    SUM(GROSS_SALES) AS GROSS_SALES,
    SUM(NET_SALES) AS NET_SALES,
    SUM(DISCOUNTS) AS DISCOUNTS,
    SUM(UNITS_SOLD) AS UNITS_SOLD,

    COUNT(DISTINCT SALE_ID) AS TRANSACTIONS,
    COUNT(DISTINCT POS_ID) AS POS_COUNT,

    -- Category mix under promo
    SUM(CASE WHEN ITEM_CATEGORY = 'FOOD' THEN NET_SALES ELSE 0 END) AS FOOD_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'NON-ALCOHOL' THEN NET_SALES ELSE 0 END) AS NA_BEV_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'BEER' THEN NET_SALES ELSE 0 END) AS BEER_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'LIQUOR' THEN NET_SALES ELSE 0 END) AS LIQUOR_SALES,
    SUM(CASE WHEN ITEM_CATEGORY = 'ALCOHOL' AND ITEM_SUBCATEGORY = 'WINE' THEN NET_SALES ELSE 0 END) AS WINE_SALES

  FROM BASE
  GROUP BY
    EVENT_DATE,
    EVENT_TYPE,
    EVENT_NAME,
    EVENT_TIER,
    SEASON,
    DAY_OF_WEEK,
    EVENT_START_TIME,
    IS_DISCOUNTED,
    DISCOUNT_NAME
)

SELECT
  EVENT_DATE,
  EVENT_TYPE,
  EVENT_NAME,
  EVENT_TIER,
  SEASON,
  DAY_OF_WEEK,
  EVENT_START_TIME,

  DISCOUNT_NAME,
  IS_DISCOUNTED,

  -- Core metrics
  GROSS_SALES,
  NET_SALES,
  DISCOUNTS,
  UNITS_SOLD,
  TRANSACTIONS,
  POS_COUNT,

  -- Discount efficiency
  DISCOUNTS / NULLIF(GROSS_SALES, 0) AS DISCOUNT_RATE,
  NET_SALES / NULLIF(TRANSACTIONS, 0) AS AVG_TICKET,
  UNITS_SOLD * 1.0 / NULLIF(TRANSACTIONS, 0) AS UNITS_PER_TXN,
  TRANSACTIONS * 1.0 / NULLIF(POS_COUNT, 0) AS TXNS_PER_POS,

  -- Mix impact (share of net sales)
  FOOD_SALES   / NULLIF(NET_SALES, 0) AS FOOD_SALES_PCT,
  NA_BEV_SALES / NULLIF(NET_SALES, 0) AS NA_BEV_SALES_PCT,
  BEER_SALES   / NULLIF(NET_SALES, 0) AS BEER_SALES_PCT,
  LIQUOR_SALES / NULLIF(NET_SALES, 0) AS LIQUOR_SALES_PCT,
  WINE_SALES   / NULLIF(NET_SALES, 0) AS WINE_SALES_PCT

FROM AGG
ORDER BY
  EVENT_DATE,
  EVENT_START_TIME,
  IS_DISCOUNTED DESC,
  NET_SALES DESC;
